services:
  db:
    image: postgres:18.3-alpine3.23@sha256:54451ecb8ab38c24c3ec123f2fd501303a3a1856a5c66e98cecf2460d5e1e9d7
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: valkey/valkey:9.0.3-alpine3.23@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5
    restart: unless-stopped
    volumes:
      - redis-data:/data

  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:4.0.8-24-trixie@sha256:58cdebfe398bd451d5f51a567a00d9880691a17a93236d2be07354b80e6e289e
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis-data:
